name: Deploy to Azure VM
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cd /home/azureuser
          sudo git clone https://github.com/tpsonu/azure-wordpress-deployment.git /var/www/html-temp
          sudo rsync -av /var/www/html-temp/ /var/www/html/ --delete
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 755 /var/www/html/
          sudo systemctl restart apache2
          echo "Deployed: $(date)" > /var/www/html/deployment.txt
