name: Deploy to Azure VM
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cd /var/www/html
          sudo git init
          sudo git remote add origin https://github.com/tpsonu/azure-wordpress-deployment.git
          sudo git fetch origin main
          sudo git reset --hard origin/main
          sudo chown -R www-data:www-data /var/www/html/
          sudo systemctl restart apache2
          echo "Deployed: $(date)" > /var/www/html/deployment.txt
